"use client";

import { useState } from "react";
import {
  Award,
  Users,
  ArrowRight,
  Sparkles,
  BookOpen,
  Download,
  Copy,
  Check,
} from "lucide-react";
import RevealOnScroll from "../RevealOnScroll";
import { callGemini } from "../../lib/gemini";

interface AcademySectionProps {
  setActiveTab: (tab: string) => void;
}

const courses = [
  {
    title: "Digital Marketing Mastery",
    level: "Beginner to Pro",
    students: "1.2k",
    color: "from-red-900 to-black",
    price: "₹4,999",
  },
  {
    title: "AI Content Creation",
    level: "Advanced",
    students: "850",
    color: "from-blue-900 to-black",
    price: "₹2,999",
  },
  {
    title: "Full Stack Agency Biz",
    level: "Expert",
    students: "400",
    color: "from-purple-900 to-black",
    price: "₹9,999",
  },
];

export default function AcademySection({ setActiveTab }: AcademySectionProps) {
  const [syllabusTopic, setSyllabusTopic] = useState("");
  const [syllabusResult, setSyllabusResult] = useState("");
  const [isGeneratingSyllabus, setIsGeneratingSyllabus] = useState(false);

  const handleGenerateSyllabus = async () => {
    if (!syllabusTopic) return;
    setIsGeneratingSyllabus(true);
    setSyllabusResult("");

    const systemPrompt =
      "You are an expert educational curriculum designer. Create a detailed 4-week learning syllabus for the requested topic. Break it down by Week 1, Week 2, Week 3, Week 4. For each week, list 3 key topics and one practical exercise. Keep the tone encouraging and professional.";
    const result = await callGemini(
      `Create a syllabus for learning: ${syllabusTopic}`,
      systemPrompt
    );

    setSyllabusResult(result);
    setIsGeneratingSyllabus(false);
  };

  const handleDownloadPDF = () => {
    if (!syllabusResult) return;

    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Rinads Academy - ${syllabusTopic || "Custom Syllabus"}</title>
            <style>
              body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #000; padding: 40px; max-width: 800px; margin: 0 auto; }
              h1 { border-bottom: 2px solid #dc2626; padding-bottom: 10px; color: #111; font-size: 28px; }
              .header { margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }
              .logo { font-weight: 900; font-size: 24px; color: #dc2626; letter-spacing: -1px; }
              .meta { font-size: 14px; color: #666; }
              pre { white-space: pre-wrap; font-family: 'Courier New', Courier, monospace; background: #f9fafb; padding: 20px; border-radius: 8px; border: 1px solid #e5e7eb; font-size: 14px; line-height: 1.6; }
              .footer { margin-top: 40px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
            </style>
          </head>
          <body>
            <div class="header">
              <div class="logo">RINADS ACADEMY</div>
              <div class="meta">Topic: <strong>${syllabusTopic}</strong></div>
            </div>
            <h1>4-Week Learning Syllabus</h1>
            <pre>${syllabusResult}</pre>
            <div class="footer">
              Generated by Rinads AI Studio • www.rinads.com
            </div>
            <script>
              window.onload = function() { window.print(); }
            </script>
          </body>
        </html>
      `);
      printWindow.document.close();
    }
  };

  return (
    <div className="min-h-screen bg-black text-white pt-28 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <RevealOnScroll>
          <div className="text-center mb-16 space-y-4">
            <div className="inline-flex items-center px-3 py-1 rounded-full bg-gray-800 text-gray-300 text-xs font-bold uppercase tracking-widest border border-gray-700">
              Education Reimagined
            </div>
            <h2 className="text-4xl md:text-5xl font-bold">
              Rinads <span className="text-red-600">Academy</span>
            </h2>
            <p className="text-gray-400 max-w-2xl mx-auto text-lg">
              Learn from the agency that&apos;s actually doing the work. Industry-recognized
              certifications and guaranteed internships for top performers.
            </p>
          </div>
        </RevealOnScroll>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
          {courses.map((course, idx) => (
            <RevealOnScroll key={idx} delay={idx * 150}>
              <div className="group relative bg-[#0a0a0a] rounded-2xl overflow-hidden border border-gray-800 hover:border-red-600/50 transition-all duration-500 hover:shadow-[0_0_30px_rgba(220,20,60,0.15)] flex flex-col hover:-translate-y-2">
                <div
                  className={`h-48 w-full bg-gradient-to-br ${course.color} relative overflow-hidden`}
                >
                  <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10"></div>
                  <div className="absolute bottom-4 left-4">
                    <span className="px-2 py-1 bg-red-600/90 backdrop-blur-md text-xs font-bold rounded text-white uppercase tracking-wider border border-red-400">
                      Live + Recorded
                    </span>
                  </div>
                </div>
                <div className="p-6 flex-1 flex flex-col">
                  <div className="mb-4">
                    <h3 className="text-xl font-bold text-white group-hover:text-red-500 transition-colors">
                      {course.title}
                    </h3>
                  </div>
                  <div className="flex items-center text-sm text-gray-400 mb-6 space-x-4">
                    <span className="flex items-center bg-gray-900 px-2 py-1 rounded border border-gray-800">
                      <Award size={14} className="mr-1 text-yellow-500" /> {course.level}
                    </span>
                    <span className="flex items-center">
                      <Users size={14} className="mr-1" /> {course.students}
                    </span>
                  </div>
                  <div className="flex items-center justify-between mt-auto pt-4 border-t border-gray-800">
                    <div className="flex flex-col">
                      <span className="text-xs text-gray-500 line-through">₹15,000</span>
                      <span className="text-2xl font-bold text-white">{course.price}</span>
                    </div>
                    <button
                      onClick={() => {
                        setActiveTab("contact");
                        window.scrollTo(0, 0);
                      }}
                      className="bg-white text-black hover:bg-red-600 hover:text-white px-4 py-2 rounded-lg text-sm font-bold flex items-center transition-all duration-300"
                    >
                      Enroll <ArrowRight size={16} className="ml-1" />
                    </button>
                  </div>
                </div>
              </div>
            </RevealOnScroll>
          ))}
        </div>

        <RevealOnScroll delay={200}>
          <div className="bg-gradient-to-b from-gray-900 to-black border border-gray-800 rounded-3xl p-8 md:p-12 mb-16 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-96 h-96 bg-red-600/10 rounded-full blur-[100px] pointer-events-none"></div>

            <div className="relative z-10">
              <div className="flex flex-col md:flex-row gap-8 items-start">
                <div className="md:w-1/3">
                  <div className="inline-flex items-center px-3 py-1 rounded-full bg-red-900/30 text-red-400 text-xs font-bold uppercase tracking-widest border border-red-900/50 mb-4">
                    <Sparkles size={12} className="mr-2" /> AI Powered
                  </div>
                  <h3 className="text-3xl font-bold text-white mb-4">
                    Design Your Custom Learning Path
                  </h3>
                  <p className="text-gray-400">
                    Not seeing the course you want? Tell our AI what you want to learn, and
                    we&apos;ll generate a personalized 4-week syllabus just for you.
                  </p>
                </div>

                <div className="md:w-2/3 w-full">
                  <div className="flex flex-col sm:flex-row gap-4 mb-6">
                    <input
                      type="text"
                      value={syllabusTopic}
                      onChange={(e) => setSyllabusTopic(e.target.value)}
                      placeholder="e.g., Dropshipping, Three.js, Public Speaking..."
                      className="flex-1 bg-black border border-gray-700 rounded-xl px-6 py-4 text-white focus:outline-none focus:border-red-500 transition-colors"
                    />
                    <button
                      onClick={handleGenerateSyllabus}
                      disabled={isGeneratingSyllabus}
                      className="bg-white text-black hover:bg-red-600 hover:text-white px-8 py-4 rounded-xl font-bold transition-all disabled:opacity-50 whitespace-nowrap flex items-center justify-center"
                    >
                      {isGeneratingSyllabus ? "Generating..." : "Generate Syllabus ✨"}
                    </button>
                  </div>

                  {syllabusResult && (
                    <div className="bg-black/50 border border-gray-800 rounded-xl p-6 animate-in fade-in slide-in-from-bottom-4">
                      <div className="flex justify-between items-center mb-4 border-b border-gray-800 pb-4">
                        <h4 className="text-lg font-bold text-white flex items-center">
                          <BookOpen className="mr-2 text-red-500" /> Your Custom 4-Week Plan
                        </h4>
                        <div className="flex gap-4">
                          <button
                            onClick={handleDownloadPDF}
                            className="text-gray-500 hover:text-white text-sm flex items-center transition-colors"
                          >
                            <Download size={14} className="mr-1" /> PDF
                          </button>
                          <button
                            onClick={() => navigator.clipboard.writeText(syllabusResult)}
                            className="text-gray-500 hover:text-white text-sm flex items-center transition-colors"
                          >
                            <Copy size={14} className="mr-1" /> Copy
                          </button>
                        </div>
                      </div>
                      <div className="prose prose-invert prose-sm max-w-none text-gray-300 whitespace-pre-wrap font-mono">
                        {syllabusResult}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </RevealOnScroll>

        <RevealOnScroll delay={400}>
          <div className="mt-20 bg-gradient-to-r from-[#0a0a0a] to-[#111] border border-gray-800 rounded-3xl p-8 md:p-12 flex flex-col md:flex-row items-center justify-between relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-red-900/20 rounded-full blur-[80px]"></div>

            <div className="md:w-2/3 mb-8 md:mb-0 relative z-10">
              <h3 className="text-3xl font-bold mb-4 text-white">Earn While You Learn</h3>
              <p className="text-gray-400 mb-6 text-lg">
                Top 5% of our academy graduates get directly placed into Rinads Agency projects
                with a paid stipend. Stop studying theory, start building your career.
              </p>
              <div className="flex flex-wrap gap-4">
                {["Live Client Projects", "1-on-1 Mentorship", "Global Certification", "Placement Guarantee"].map(
                  (tag) => (
                    <span
                      key={tag}
                      className="flex items-center text-gray-300 bg-gray-900/80 px-4 py-2 rounded-full text-sm border border-gray-700"
                    >
                      <Check size={14} className="text-green-500 mr-2" /> {tag}
                    </span>
                  )
                )}
              </div>
            </div>
            <div className="md:w-1/3 flex justify-center relative z-10">
              <button
                onClick={() => {
                  setActiveTab("contact");
                  window.scrollTo(0, 0);
                }}
                className="w-40 h-40 rounded-full bg-gradient-to-br from-red-600 to-red-800 flex items-center justify-center animate-[bounce_3s_infinite] shadow-[0_0_40px_rgba(220,20,60,0.6)] border-4 border-black hover:scale-110 transition-transform cursor-pointer"
              >
                <div className="text-center">
                  <span className="block text-white font-bold text-lg">Apply for</span>
                  <span className="block text-white font-black text-xl uppercase">Internship</span>
                </div>
              </button>
            </div>
          </div>
        </RevealOnScroll>
      </div>
    </div>
  );
}

